version: "3.7"
services:
  # ration_master_db:
  #   image: keinos/sqlite3:latest
  #   container_name: ration_master_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - "sqlite_data:/workspace"
  ration_master_backend:
    container_name: rm_backend
    build:
      context: .
    volumes:
      - sqlite_data:/sqlite_data/
    environment:
      - DATABASE_URL=sqlite:////sqlite_data/sqlite.db
    ports:
      - "8080:8080"
volumes:
  sqlite_data:
